### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by tzdy1993** [AzerPUG/ToolTips#23] opened 2022-03-22 22:50 UTC
AddOns\AzerPUGsToolTips\ToolTips.lua:184: attempt to index local 'text' (a nil value)
Count: 3

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\AzerPUGsToolTips\ToolTips.lua"]:184: in function `SearchGenericUpgradeableItem'
[string "@AddOns\AzerPUGsToolTips\ToolTips.lua"]:15: in function <AddOns\AzerPUGsToolTips\ToolTips.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
[string "=[C]"]: ?

**Comment by Arco-Dielhof** [comment] 2022-03-23 07:19
Heyya! Thank you for copy pasting the error in, could you let us know what item you got the error on?

We have not seen one of these in a very **_very_** long time, so it is probably an edge case we need to write some extra code for.

**Comment by Arco-Dielhof** [comment] 2022-04-20 13:19
Since we have not been able to reproduce, not haven anyone else report this, nor had a reaction for almost a month, I am closing this issue for now.
If you have it again, please, do not hesitate to re open it!

**Closed as completed by Arco-Dielhof** 2022-04-20 13:19 UTC
